name: Python lint

on:
  pull_request:
    branches:
      - main
    paths:
      - '**/*.py'
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  python-lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Ruff
        run: pip install ruff==0.16.1

      - name: Run Ruff
        run: |
          ruff check .